export interface Shoe {
  id: string;
  brand: string;
  model: string;
  year: number;
  category: 'daily' | 'speed' | 'race' | 'trail' | 'max-cushion' | 'stability' | 'hybrid';
  cushioning: number; // 1-10
  dropMM: number;
  weightGrams: number;
  pronation: ('neutral' | 'overpronation' | 'underpronation')[];
  terrain: ('road' | 'trail' | 'track')[];
  bestDistances: string[];
  bestFor: string[];
  widthOptions: boolean;
  priceUSD: number;
  injuryFriendly: string[];
  amazonASIN: string;
  reviewURL: string;
  imageURL: string;
  highlights: string[];
  /**
   * URL of the manufacturer (or first-party retailer) page where the specs
   * above can be independently verified. Optional — defaults to a brand
   * search if missing. Used by the validation script and surfaced as a
   * "Verified spec source" link in the UI.
   */
  sourceURL?: string;
  /**
   * ISO date (YYYY-MM-DD) when the specs above were last cross-checked
   * against the manufacturer source. Optional. The validation script flags
   * any entry older than 180 days.
   */
  lastVerified?: string;
}

export const shoeDatabase: Shoe[] = [
  // === NIKE ===
  {
    id: 'nike-pegasus-41',
    brand: 'Nike',
    model: 'Pegasus 41',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 285,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['beginner', 'daily', 'long-run'],
    widthOptions: true,
    priceUSD: 130,
    injuryFriendly: ['knee-pain', 'shin-splints'],
    amazonASIN: 'B0D5Y2KZQH',
    reviewURL: 'https://gearuptofit.com/review/nike-pegasus-41/',
    imageURL: '/images/shoes/nike-pegasus-41.jpg',
    highlights: ['ReactX foam', 'Versatile all-rounder', 'Great for beginners'],
    sourceURL: 'https://www.nike.com/t/pegasus-41-mens-road-running-shoes-MdxBSc',
    lastVerified: '2026-05-04',
  },
  {
    id: 'nike-pegasus-premium',
    brand: 'Nike',
    model: 'Pegasus Premium',
    year: 2025,
    category: 'daily',
    cushioning: 8,
    dropMM: 10,
    weightGrams: 275,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 180,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0DFLY4TQX',
    reviewURL: 'https://gearuptofit.com/review/nike-pegasus-premium/',
    imageURL: '/images/shoes/nike-pegasus-premium.jpg',
    highlights: ['ZoomX foam', 'Premium daily trainer', 'Plush ride'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nike-vomero-plus',
    brand: 'Nike',
    model: 'Vomero Plus',
    year: 2025,
    category: 'max-cushion',
    cushioning: 9,
    dropMM: 10,
    weightGrams: 305,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 180,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'],
    amazonASIN: 'B0DG1RSLWZ',
    reviewURL: 'https://gearuptofit.com/review/nike-vomero-plus/',
    imageURL: '/images/shoes/nike-vomero-plus.jpg',
    highlights: ['ZoomX midsole', 'Max cushion', 'Injury-friendly'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nike-pegasus-turbo',
    brand: 'Nike',
    model: 'Pegasus Turbo',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 8,
    weightGrams: 230,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'race-day'],
    widthOptions: false,
    priceUSD: 190,
    injuryFriendly: [],
    amazonASIN: 'B0DFLYH8QX',
    reviewURL: 'https://gearuptofit.com/review/running-shoes/nike-pegasus-turbo-review/',
    imageURL: '/images/shoes/nike-pegasus-turbo.jpg',
    highlights: ['ZoomX + React', 'Lightweight', 'Speed sessions'],
    lastVerified: '2026-05-04',
  },
  // === BROOKS ===
  {
    id: 'brooks-ghost-17',
    brand: 'Brooks',
    model: 'Ghost 17',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 12,
    weightGrams: 290,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['beginner', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['achilles', 'shin-splints'],
    amazonASIN: 'B0CX3T1GRV',
    reviewURL: 'https://gearuptofit.com/review/brooks-ghost-17/',
    imageURL: '/images/shoes/brooks-ghost-17.jpg',
    highlights: ['DNA LOFT v2', 'Smooth transitions', 'Classic neutral'],
    sourceURL: 'https://www.brooksrunning.com/en_us/ghost-17-mens-road-running-shoes/110441.html',
    lastVerified: '2026-05-04',
  },
  {
    id: 'brooks-glycerin-max-2',
    brand: 'Brooks',
    model: 'Glycerin Max 2',
    year: 2025,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 10,
    weightGrams: 310,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 170,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'],
    amazonASIN: 'B0D8Y4JQRV',
    reviewURL: 'https://gearuptofit.com/review/brooks-glycerin-max-2/',
    imageURL: '/images/shoes/brooks-glycerin-max-2.jpg',
    highlights: ['Nitrogen-infused foam', 'Ultra plush', 'Max stack height'],
    lastVerified: '2026-05-04',
  },
  // === ASICS ===
  {
    id: 'asics-gel-nimbus-28',
    brand: 'Asics',
    model: 'Gel-Nimbus 28',
    year: 2025,
    category: 'daily',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 295,
    pronation: ['neutral', 'underpronation'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 160,
    injuryFriendly: ['knee-pain', 'plantar-fasciitis'],
    amazonASIN: 'B0CWG4XFQH',
    reviewURL: 'https://gearuptofit.com/review/asics-gel-nimbus-28/',
    imageURL: '/images/shoes/asics-gel-nimbus-28.jpg',
    highlights: ['FF BLAST PLUS ECO', 'PureGEL heel', 'Plush comfort'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-gel-kayano-32',
    brand: 'Asics',
    model: 'Gel-Kayano 32',
    year: 2025,
    category: 'stability',
    cushioning: 8,
    dropMM: 10,
    weightGrams: 310,
    pronation: ['overpronation'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 160,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'it-band'],
    amazonASIN: 'B0D4X7KLQH',
    reviewURL: 'https://gearuptofit.com/review/running-shoes/asics-mens-gel-kayano-32/',
    imageURL: '/images/shoes/asics-gel-kayano-32.jpg',
    highlights: ['4D Guidance System', 'FF BLAST PLUS', 'Premium stability'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-novablast-5',
    brand: 'Asics',
    model: 'Novablast 5',
    year: 2025,
    category: 'speed',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 260,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'daily'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0D6Y3KFQH',
    reviewURL: 'https://gearuptofit.com/review/asics-novablast-5/',
    imageURL: '/images/shoes/asics-novablast-5.jpg',
    highlights: ['FF BLAST PLUS', 'Bouncy ride', 'Tempo sessions'],
    sourceURL: 'https://www.asics.com/us/en-us/novablast-5/p/1011B868.html',
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-novablast-4',
    brand: 'Asics',
    model: 'Novablast 4',
    year: 2024,
    category: 'daily',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 265,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'speed-work'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0CTKR8QQH',
    reviewURL: 'https://gearuptofit.com/review/asics-novablast-4/',
    imageURL: '/images/shoes/asics-novablast-4.jpg',
    highlights: ['FF BLAST PLUS', 'Versatile', 'Great value'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-superblast-3',
    brand: 'Asics',
    model: 'Superblast 3',
    year: 2025,
    category: 'race',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 240,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 200,
    injuryFriendly: [],
    amazonASIN: 'B0DG2RKLQH',
    reviewURL: 'https://gearuptofit.com/review/asics-superblast-3/',
    imageURL: '/images/shoes/asics-superblast-3.jpg',
    highlights: ['FF TURBO PLUS', 'Carbon plate', 'Super trainer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-sonicblast',
    brand: 'Asics',
    model: 'Sonicblast',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 8,
    weightGrams: 235,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k'],
    bestFor: ['speed-work', 'race-day'],
    widthOptions: false,
    priceUSD: 160,
    injuryFriendly: [],
    amazonASIN: 'B0DH3RMLQH',
    reviewURL: 'https://gearuptofit.com/review/asics-sonicblast/',
    imageURL: '/images/shoes/asics-sonicblast.jpg',
    highlights: ['Lightweight racer', 'Fast turnover', 'Track-ready'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-megablast',
    brand: 'Asics',
    model: 'Megablast',
    year: 2025,
    category: 'max-cushion',
    cushioning: 9,
    dropMM: 8,
    weightGrams: 295,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 180,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain'],
    amazonASIN: 'B0DI4RNLQH',
    reviewURL: 'https://gearuptofit.com/review/asics-megablast/',
    imageURL: '/images/shoes/asics-megablast.jpg',
    highlights: ['Max stack', 'FF BLAST PLUS ECO', 'Ultra cushioned'],
    lastVerified: '2026-05-04',
  },
  // === HOKA ===
  {
    id: 'hoka-bondi-9',
    brand: 'Hoka',
    model: 'Bondi 9',
    year: 2025,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 4,
    weightGrams: 310,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['beginner', 'long-run', 'daily'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'achilles'],
    amazonASIN: 'B0DG5RPLQH',
    reviewURL: 'https://gearuptofit.com/review/hoka-bondi-9/',
    imageURL: '/images/shoes/hoka-bondi-9.jpg',
    highlights: ['Ultra-cushioned', 'Meta-Rocker', 'Recovery-friendly'],
    sourceURL: 'https://www.hoka.com/en/us/mens-road/bondi-9/1147010.html',
    lastVerified: '2026-05-04',
  },
  {
    id: 'hoka-cielo-x1-3',
    brand: 'Hoka',
    model: 'Cielo X1 3',
    year: 2025,
    category: 'race',
    cushioning: 6,
    dropMM: 5,
    weightGrams: 195,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'B0DH6RQLQH',
    reviewURL: 'https://gearuptofit.com/review/hoka-cielo-x1-3/',
    imageURL: '/images/shoes/hoka-cielo-x1-3.jpg',
    highlights: ['Carbon plate', 'PEBA foam', 'Race-day weapon'],
    lastVerified: '2026-05-04',
  },
  // === SAUCONY ===
  {
    id: 'saucony-ride-19',
    brand: 'Saucony',
    model: 'Ride 19',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 270,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['beginner', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['shin-splints'],
    amazonASIN: 'B0D7Y5KLQH',
    reviewURL: 'https://gearuptofit.com/review/saucony-ride-19/',
    imageURL: '/images/shoes/saucony-ride-19.jpg',
    highlights: ['PWRRUN+', 'Smooth ride', 'Versatile trainer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'saucony-endorphin-azura',
    brand: 'Saucony',
    model: 'Endorphin Azura',
    year: 2025,
    category: 'race',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 210,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 230,
    injuryFriendly: [],
    amazonASIN: 'B0DI7RSLQH',
    reviewURL: 'https://gearuptofit.com/review/saucony-endorphin-azura/',
    imageURL: '/images/shoes/saucony-endorphin-azura.jpg',
    highlights: ['Carbon plate', 'PWRRUN HG', 'Elite racer'],
    lastVerified: '2026-05-04',
  },
  // === ON ===
  {
    id: 'on-cloudsurfer-2',
    brand: 'On',
    model: 'Cloudsurfer 2',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'beginner'],
    widthOptions: false,
    priceUSD: 150,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0CX5T3GRV',
    reviewURL: 'https://gearuptofit.com/review/on-cloudsurfer-2/',
    imageURL: '/images/shoes/on-cloudsurfer-2.jpg',
    highlights: ['CloudTec Phase', 'Helion HF', 'Swiss engineering'],
    lastVerified: '2026-05-04',
  },
  // === ADIDAS ===
  {
    id: 'adidas-adios-pro-4',
    brand: 'Adidas',
    model: 'Adios Pro 4',
    year: 2025,
    category: 'race',
    cushioning: 7,
    dropMM: 7,
    weightGrams: 195,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race-day'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'B0D9Y6MLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-adios-pro-4/',
    imageURL: '/images/shoes/adidas-adios-pro-4.jpg',
    highlights: ['ENERGYRODS 2.0', 'LIGHTSTRIKE PRO', 'Marathon weapon'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-adios-9',
    brand: 'Adidas',
    model: 'Adios 9',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 7,
    weightGrams: 235,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'race-day'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0DAY7NLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-adios-9/',
    imageURL: '/images/shoes/adidas-adios-9.jpg',
    highlights: ['LIGHTSTRIKE PRO', 'Glass fiber rods', 'Tempo specialist'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-boston-13',
    brand: 'Adidas',
    model: 'Boston 13',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 7,
    weightGrams: 245,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0DBY8PLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-adizero-boston-13/',
    imageURL: '/images/shoes/adidas-boston-13.jpg',
    highlights: ['LIGHTSTRIKE PRO', 'Energyrods', 'Fast daily trainer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-evo-sl',
    brand: 'Adidas',
    model: 'EVO SL',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 275,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'beginner'],
    widthOptions: true,
    priceUSD: 120,
    injuryFriendly: ['shin-splints'],
    amazonASIN: 'B0DCY9QLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-evo-sl/',
    imageURL: '/images/shoes/adidas-evo-sl.jpg',
    highlights: ['DREAMSTRIKE+', 'Affordable', 'Great first shoe'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-evo-sl-atr',
    brand: 'Adidas',
    model: 'EVO SL ATR',
    year: 2025,
    category: 'hybrid',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 290,
    pronation: ['neutral'],
    terrain: ['road', 'trail'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily'],
    widthOptions: false,
    priceUSD: 130,
    injuryFriendly: [],
    amazonASIN: 'B0DDY0RLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-evo-sl-atr/',
    imageURL: '/images/shoes/adidas-evo-sl-atr.jpg',
    highlights: ['Continental rubber', 'Road-to-trail', 'Hybrid outsole'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-takumi-sen-11',
    brand: 'Adidas',
    model: 'Takumi Sen 11',
    year: 2025,
    category: 'race',
    cushioning: 4,
    dropMM: 6,
    weightGrams: 175,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 180,
    injuryFriendly: [],
    amazonASIN: 'B0DEY1SLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-takumi-sen-11/',
    imageURL: '/images/shoes/adidas-takumi-sen-11.jpg',
    highlights: ['Ultra lightweight', 'LIGHTSTRIKE PRO', 'Racing flat'],
    lastVerified: '2026-05-04',
  },
  // === PUMA ===
  {
    id: 'puma-deviate-elite-4',
    brand: 'Puma',
    model: 'Deviate Elite 4',
    year: 2025,
    category: 'race',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 205,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race-day'],
    widthOptions: false,
    priceUSD: 230,
    injuryFriendly: [],
    amazonASIN: 'B0DFY2TLQH',
    reviewURL: 'https://gearuptofit.com/review/puma-deviate-elite-4/',
    imageURL: '/images/shoes/puma-deviate-elite-4.jpg',
    highlights: ['NITRO ELITE foam', 'Carbon plate', 'Race day'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'puma-deviate-nitro-elite-2',
    brand: 'Puma',
    model: 'Deviate Nitro Elite 2',
    year: 2024,
    category: 'race',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 210,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 220,
    injuryFriendly: [],
    amazonASIN: 'B0CGY3ULQH',
    reviewURL: 'https://gearuptofit.com/review/puma-deviate-nitro-elite-2-review/',
    imageURL: '/images/shoes/puma-deviate-nitro-elite-2.jpg',
    highlights: ['NITRO ELITE', 'Carbon plate', 'Proven racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'puma-magmax-2',
    brand: 'Puma',
    model: 'Magmax 2',
    year: 2025,
    category: 'daily',
    cushioning: 8,
    dropMM: 10,
    weightGrams: 285,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0DGY4VLQH',
    reviewURL: 'https://gearuptofit.com/review/puma-magmax-2/',
    imageURL: '/images/shoes/puma-magmax-2.jpg',
    highlights: ['NITRO foam', 'Cushioned daily', 'Comfortable'],
    lastVerified: '2026-05-04',
  },
  // === NEW BALANCE ===
  {
    id: 'nb-fresh-foam-more-v6',
    brand: 'New Balance',
    model: 'Fresh Foam X More v6',
    year: 2025,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 4,
    weightGrams: 320,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'achilles'],
    amazonASIN: 'B0DHY5WLQH',
    reviewURL: 'https://gearuptofit.com/review/new-balance-fresh-foam-x-more-v6/',
    imageURL: '/images/shoes/nb-more-v6.jpg',
    highlights: ['Fresh Foam X', 'Maximum stack', 'Recovery runs'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nb-1080-v14',
    brand: 'New Balance',
    model: '1080 v14',
    year: 2024,
    category: 'daily',
    cushioning: 8,
    dropMM: 6,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['knee-pain', 'plantar-fasciitis'],
    amazonASIN: 'B0CTKR9QQH',
    reviewURL: 'https://gearuptofit.com/review/new-balance-1080-v14/',
    imageURL: '/images/shoes/nb-1080-v14.jpg',
    highlights: ['Fresh Foam X', 'Premium daily', 'Buttery smooth'],
    lastVerified: '2026-05-04',
  },
  // === SALOMON (TRAIL) ===
  {
    id: 'salomon-speedcross-6',
    brand: 'Salomon',
    model: 'Speedcross 6',
    year: 2024,
    category: 'trail',
    cushioning: 6,
    dropMM: 10,
    weightGrams: 310,
    pronation: ['neutral', 'overpronation'],
    terrain: ['trail'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['trail', 'daily'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0BZK8GQFH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/salomon-speedcross-6.jpg',
    highlights: ['Contagrip MA', 'Aggressive lugs', 'Mud & soft terrain'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'salomon-ultra-glide-3',
    brand: 'Salomon',
    model: 'Ultra Glide 3',
    year: 2025,
    category: 'trail',
    cushioning: 8,
    dropMM: 6,
    weightGrams: 290,
    pronation: ['neutral'],
    terrain: ['trail'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'trail'],
    widthOptions: false,
    priceUSD: 160,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0D4X8KLQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/salomon-ultra-glide-3.jpg',
    highlights: ['Energy Foam', 'Contagrip', 'Ultra-distance trail'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'salomon-sense-ride-6',
    brand: 'Salomon',
    model: 'Sense Ride 6',
    year: 2025,
    category: 'hybrid',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 275,
    pronation: ['neutral'],
    terrain: ['trail', 'road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['trail', 'daily'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0D5Y3MLQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/salomon-sense-ride-6.jpg',
    highlights: ['Road-to-trail', 'Optivibe', 'Versatile hybrid'],
    lastVerified: '2026-05-04',
  },
  // === ALTRA (ZERO DROP) ===
  {
    id: 'altra-lone-peak-8',
    brand: 'Altra',
    model: 'Lone Peak 8',
    year: 2024,
    category: 'trail',
    cushioning: 7,
    dropMM: 0,
    weightGrams: 305,
    pronation: ['neutral', 'underpronation'],
    terrain: ['trail'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['trail', 'long-run'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['plantar-fasciitis'],
    amazonASIN: 'B0CTKR7QQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/altra-lone-peak-8.jpg',
    highlights: ['Zero drop', 'FootShape toe box', 'Trail icon'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'altra-torin-7',
    brand: 'Altra',
    model: 'Torin 7',
    year: 2024,
    category: 'daily',
    cushioning: 8,
    dropMM: 0,
    weightGrams: 270,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 150,
    injuryFriendly: ['plantar-fasciitis', 'achilles'],
    amazonASIN: 'B0CTKR6QQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/altra-torin-7.jpg',
    highlights: ['Zero drop', 'Wide toe box', 'Natural running'],
    lastVerified: '2026-05-04',
  },
  // === MIZUNO ===
  {
    id: 'mizuno-wave-rider-28',
    brand: 'Mizuno',
    model: 'Wave Rider 28',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 12,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'beginner'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['shin-splints'],
    amazonASIN: 'B0D8Y5NLQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/mizuno-wave-rider-28.jpg',
    highlights: ['Mizuno Enerzy', 'Wave plate', 'Smooth transition'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'mizuno-wave-inspire-21',
    brand: 'Mizuno',
    model: 'Wave Inspire 21',
    year: 2025,
    category: 'stability',
    cushioning: 7,
    dropMM: 12,
    weightGrams: 295,
    pronation: ['overpronation'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 150,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'],
    amazonASIN: 'B0D9Y6PLQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/mizuno-wave-inspire-21.jpg',
    highlights: ['Wave plate stability', 'Enerzy foam', 'Overpronation support'],
    lastVerified: '2026-05-04',
  },
  // === BROOKS STABILITY ===
  {
    id: 'brooks-adrenaline-gts-25',
    brand: 'Brooks',
    model: 'Adrenaline GTS 25',
    year: 2025,
    category: 'stability',
    cushioning: 7,
    dropMM: 12,
    weightGrams: 290,
    pronation: ['overpronation'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['beginner', 'daily', 'long-run'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'it-band'],
    amazonASIN: 'B0D7Y6QLQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/brooks-adrenaline-gts-25.jpg',
    highlights: ['GuideRails support', 'DNA LOFT v2', 'Gold standard stability'],
    lastVerified: '2026-05-04',
  },
  // === HOKA TRAIL ===
  {
    id: 'hoka-speedgoat-6',
    brand: 'Hoka',
    model: 'Speedgoat 6',
    year: 2025,
    category: 'trail',
    cushioning: 8,
    dropMM: 4,
    weightGrams: 295,
    pronation: ['neutral'],
    terrain: ['trail'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['trail', 'long-run'],
    widthOptions: true,
    priceUSD: 155,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0DG6RSLQH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/hoka-speedgoat-6.jpg',
    highlights: ['Vibram Megagrip', 'Max cushion trail', 'Ultra-ready'],
    lastVerified: '2026-05-04',
  },
  // === EXPANDED CATALOG: ELITE RACING ===
  {
    id: 'nike-alphafly-3',
    brand: 'Nike',
    model: 'Alphafly 3',
    year: 2024,
    category: 'race',
    cushioning: 9,
    dropMM: 8,
    weightGrams: 200,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['marathon', 'half-marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 285,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['ZoomX + Air Zoom pods', 'World record marathon shoe', 'Elite carbon plate'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nike-vaporfly-3',
    brand: 'Nike',
    model: 'Vaporfly 3',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 196,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 260,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['ZoomX foam', 'Carbon Flyplate', 'Lightning fast'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nike-streakfly',
    brand: 'Nike',
    model: 'Streakfly',
    year: 2024,
    category: 'race',
    cushioning: 6,
    dropMM: 6,
    weightGrams: 170,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k'],
    bestFor: ['race', 'speed'],
    widthOptions: false,
    priceUSD: 170,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Ultra-light', '5K/10K specialist', 'Pebax plate'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-adios-pro-3',
    brand: 'Adidas',
    model: 'Adizero Adios Pro 3',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 6,
    weightGrams: 215,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Lightstrike Pro', 'EnergyRods 2.0', 'Elite marathon weapon'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-takumi-sen-10',
    brand: 'Adidas',
    model: 'Adizero Takumi Sen 10',
    year: 2024,
    category: 'race',
    cushioning: 6,
    dropMM: 6,
    weightGrams: 170,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k'],
    bestFor: ['race', 'speed', 'tempo'],
    widthOptions: false,
    priceUSD: 200,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Carbon EnergyRods', 'Short-distance racer', 'Aggressive geometry'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-boston-12',
    brand: 'Adidas',
    model: 'Adizero Boston 12',
    year: 2024,
    category: 'speed',
    cushioning: 7,
    dropMM: 6,
    weightGrams: 245,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['tempo', 'long-run', 'race'],
    widthOptions: false,
    priceUSD: 160,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Lightstrike Pro + EnergyRods', 'Daily trainer-racer', 'Workhorse for tempo days'],
    lastVerified: '2026-05-04',
  },
  // === HOKA EXPANDED ===
  {
    id: 'hoka-mach-6',
    brand: 'Hoka',
    model: 'Mach 6',
    year: 2024,
    category: 'speed',
    cushioning: 7,
    dropMM: 5,
    weightGrams: 235,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['tempo', 'speed', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Supercritical foam', 'Snappy & responsive', 'Best value tempo shoe'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'hoka-rocket-x-2',
    brand: 'Hoka',
    model: 'Rocket X 2',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 5,
    weightGrams: 215,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Carbon plate', 'PEBA midsole', 'Hoka\'s flagship racer'],
    lastVerified: '2026-05-04',
  },
  // === SAUCONY EXPANDED ===
  {
    id: 'saucony-endorphin-pro-4',
    brand: 'Saucony',
    model: 'Endorphin Pro 4',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 215,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 225,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['PWRRUN PB foam', 'Carbon plate', 'Smooth Speedroll geometry'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'saucony-triumph-22',
    brand: 'Saucony',
    model: 'Triumph 22',
    year: 2024,
    category: 'max-cushion',
    cushioning: 9,
    dropMM: 10,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'recovery'],
    widthOptions: true,
    priceUSD: 160,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['PWRRUN+ foam', 'Plush daily max-cushion', 'Long-run comfort'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'saucony-kinvara-15',
    brand: 'Saucony',
    model: 'Kinvara 15',
    year: 2024,
    category: 'speed',
    cushioning: 6,
    dropMM: 4,
    weightGrams: 215,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed', 'tempo', 'natural-foot'],
    widthOptions: false,
    priceUSD: 120,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Lightweight uptempo', 'PWRRUN foam', 'Natural feel'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'saucony-peregrine-14',
    brand: 'Saucony',
    model: 'Peregrine 14',
    year: 2024,
    category: 'trail',
    cushioning: 6,
    dropMM: 4,
    weightGrams: 270,
    pronation: ['neutral'],
    terrain: ['trail'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['trail', 'technical-terrain'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['PWRTRAC outsole', 'Aggressive lugs', 'Trail all-rounder'],
    lastVerified: '2026-05-04',
  },
  // === ON RUNNING ===
  {
    id: 'on-cloudboom-strike',
    brand: 'On',
    model: 'Cloudboom Strike',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 4,
    weightGrams: 210,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 240,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Helion HF supercritical', 'Speedboard plate', 'Swiss precision racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'on-cloudsurfer-next',
    brand: 'On',
    model: 'Cloudsurfer Next',
    year: 2024,
    category: 'daily',
    cushioning: 7,
    dropMM: 9,
    weightGrams: 260,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: false,
    priceUSD: 160,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['CloudTec Phase', 'Smooth modern ride', 'Versatile daily'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'on-cloudmonster-2',
    brand: 'On',
    model: 'Cloudmonster 2',
    year: 2024,
    category: 'max-cushion',
    cushioning: 9,
    dropMM: 6,
    weightGrams: 290,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'recovery'],
    widthOptions: false,
    priceUSD: 180,
    injuryFriendly: ['knee-pain', 'shin-splints'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Massive CloudTec', 'Plush long-run partner', 'Distinctive look'],
    lastVerified: '2026-05-04',
  },
  // === ASICS EXPANDED ===
  {
    id: 'asics-superblast-2',
    brand: 'ASICS',
    model: 'Superblast 2',
    year: 2024,
    category: 'speed',
    cushioning: 9,
    dropMM: 8,
    weightGrams: 245,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'tempo', 'long-run'],
    widthOptions: false,
    priceUSD: 200,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['FF Turbo+ FF Blast Plus', 'Plateless supershoe feel', 'Cult favorite'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-magic-speed-4',
    brand: 'ASICS',
    model: 'Magic Speed 4',
    year: 2024,
    category: 'speed',
    cushioning: 7,
    dropMM: 7,
    weightGrams: 230,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['tempo', 'race', 'speed'],
    widthOptions: false,
    priceUSD: 160,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Carbon plate at value price', 'FF Blast Plus', 'Race-day backup'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-metaspeed-sky-paris',
    brand: 'ASICS',
    model: 'Metaspeed Sky Paris',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 5,
    weightGrams: 190,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['FF Turbo+ midsole', 'Carbon plate', 'For striders'],
    lastVerified: '2026-05-04',
  },
  // === NEW BALANCE EXPANDED ===
  {
    id: 'nb-fuelcell-supercomp-elite-v4',
    brand: 'New Balance',
    model: 'FuelCell SuperComp Elite v4',
    year: 2024,
    category: 'race',
    cushioning: 9,
    dropMM: 4,
    weightGrams: 230,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['PEBA FuelCell foam', 'Energy Arc carbon plate', 'Stack monster racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nb-fresh-foam-x-more-v5',
    brand: 'New Balance',
    model: 'Fresh Foam X More v5',
    year: 2024,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 4,
    weightGrams: 295,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['recovery', 'long-run', 'daily'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'achilles'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Massive Fresh Foam X', 'Recovery champion', 'Pillowy ride'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nb-fresh-foam-1080-v14',
    brand: 'New Balance',
    model: 'Fresh Foam X 1080 v14',
    year: 2024,
    category: 'daily',
    cushioning: 9,
    dropMM: 6,
    weightGrams: 275,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'beginner'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['knee-pain', 'shin-splints', 'plantar-fasciitis'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Premium Fresh Foam X', 'Wide-fit available', 'All-day comfort'],
    lastVerified: '2026-05-04',
  },
  // === BROOKS EXPANDED ===
  {
    id: 'brooks-hyperion-elite-4',
    brand: 'Brooks',
    model: 'Hyperion Elite 4',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 215,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['DNA Gold supercritical foam', 'Carbon SpeedVault plate', 'Brooks\' fastest shoe'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'brooks-hyperion-max-2',
    brand: 'Brooks',
    model: 'Hyperion Max 2',
    year: 2024,
    category: 'speed',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 240,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['tempo', 'speed'],
    widthOptions: false,
    priceUSD: 170,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Plateless tempo trainer', 'DNA Flash v2', 'Smooth uptempo'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'brooks-cascadia-18',
    brand: 'Brooks',
    model: 'Cascadia 18',
    year: 2024,
    category: 'trail',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 295,
    pronation: ['neutral', 'overpronation'],
    terrain: ['trail'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['trail', 'beginner', 'mixed-terrain'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Trail Adapt System', 'Stable & protective', 'Beginner-friendly trail'],
    lastVerified: '2026-05-04',
  },
  // === PUMA ===
  {
    id: 'puma-deviate-nitro-elite-3',
    brand: 'Puma',
    model: 'Deviate Nitro Elite 3',
    year: 2024,
    category: 'race',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 200,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race', 'pr-attempt'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['NITRO Elite + A-PLATE', 'PWRPLATE carbon', 'Sub-200g speed'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'puma-velocity-nitro-3',
    brand: 'Puma',
    model: 'Velocity Nitro 3',
    year: 2024,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 270,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'beginner'],
    widthOptions: false,
    priceUSD: 130,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['NITRO foam', 'Best value daily trainer', 'PUMAGRIP outsole'],
    lastVerified: '2026-05-04',
  },
  // === TRAIL SPECIALISTS ===
  {
    id: 'inov8-trailfly-ultra-g-300',
    brand: 'Inov-8',
    model: 'TrailFly Ultra G 300 Max',
    year: 2024,
    category: 'trail',
    cushioning: 8,
    dropMM: 6,
    weightGrams: 300,
    pronation: ['neutral'],
    terrain: ['trail'],
    bestDistances: ['marathon', 'ultra'],
    bestFor: ['trail', 'ultra', 'long-run'],
    widthOptions: true,
    priceUSD: 190,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Graphene-grip outsole', 'Ultra-distance trail', 'Wide toe box'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'merrell-agility-peak-5',
    brand: 'Merrell',
    model: 'Agility Peak 5',
    year: 2024,
    category: 'trail',
    cushioning: 7,
    dropMM: 6,
    weightGrams: 295,
    pronation: ['neutral'],
    terrain: ['trail'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['trail', 'mixed-terrain'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Vibram Megagrip', 'FloatPro Foam', 'Versatile trail'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'topo-mtn-racer-3',
    brand: 'Topo Athletic',
    model: 'MTN Racer 3',
    year: 2024,
    category: 'trail',
    cushioning: 7,
    dropMM: 5,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['trail'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['trail', 'ultra', 'wide-feet'],
    widthOptions: true,
    priceUSD: 160,
    injuryFriendly: ['plantar-fasciitis'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Vibram XS Trek EVO', 'Roomy toe box', 'Low drop natural feel'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'topo-cyclone-2',
    brand: 'Topo Athletic',
    model: 'Cyclone 2',
    year: 2024,
    category: 'speed',
    cushioning: 7,
    dropMM: 5,
    weightGrams: 215,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed', 'tempo', 'wide-feet', 'natural-foot'],
    widthOptions: true,
    priceUSD: 150,
    injuryFriendly: [],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['ZipFoam supercritical', 'Roomy uptempo trainer', 'Low drop'],
    lastVerified: '2026-05-04',
  },
  // === MAY 2026 ADDITIONS — backed by latest GearUpToFit reviews ===
  {
    id: 'nike-pegasus-42',
    brand: 'Nike', model: 'Pegasus 42', year: 2026, category: 'daily',
    cushioning: 7, dropMM: 10, weightGrams: 280,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'beginner', 'long-run'], widthOptions: true, priceUSD: 140,
    injuryFriendly: ['knee-pain', 'shin-splints'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/nike-pegasus-42/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Curved full-length Air Zoom', 'ReactX midsole', 'Roomier forefoot'],
    sourceURL: 'https://www.nike.com/t/pegasus-42-mens-road-running-shoes',
    lastVerified: '2026-05-04',
  },
  {
    id: 'hoka-clifton-10',
    brand: 'Hoka', model: 'Clifton 10', year: 2026, category: 'daily',
    cushioning: 8, dropMM: 8, weightGrams: 272,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'beginner', 'long-run', 'recovery'], widthOptions: true, priceUSD: 150,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'achilles'],
    amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/hoka-clifton-10/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Plush daily trainer', 'Smooth Meta-Rocker', 'Roomier everyday fit'],
    sourceURL: 'https://www.hoka.com/en/us/mens-road/clifton-10/',
    lastVerified: '2026-05-04',
  },
  {
    id: 'hoka-skyward-x',
    brand: 'Hoka', model: 'Skyward X', year: 2026, category: 'max-cushion',
    cushioning: 10, dropMM: 5, weightGrams: 326,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'recovery'], widthOptions: false, priceUSD: 225,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'achilles'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/hoka-skyward-x/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Carbon-plated super trainer', 'Max-cushion stack', 'Easy-mile rocker'],
    sourceURL: 'https://www.hoka.com/en/us/mens-road/skyward-x/',
    lastVerified: '2026-05-04',
  },
  {
    id: 'lining-feidian-6-elite',
    brand: 'Li-Ning', model: 'Feidian 6 Elite', year: 2026, category: 'race',
    cushioning: 8, dropMM: 6, weightGrams: 205,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'], widthOptions: false, priceUSD: 230,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/li-ning-feidian-6-elite/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Full-length carbon plate', 'Super BOOM foam', 'Marathon racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-gel-nimbus-29',
    brand: 'ASICS', model: 'Gel-Nimbus 29', year: 2026, category: 'max-cushion',
    cushioning: 10, dropMM: 8, weightGrams: 295,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'recovery'], widthOptions: true, priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['FF Blast Max foam', 'Plush max-cushion', 'Daily long-run'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-novablast-6',
    brand: 'ASICS', model: 'Novablast 6', year: 2026, category: 'daily',
    cushioning: 8, dropMM: 8, weightGrams: 255,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'tempo', 'long-run'], widthOptions: false, priceUSD: 145,
    injuryFriendly: ['knee-pain'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Bouncy FF Blast Max', 'Versatile do-it-all', 'Trampoline ride'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'asics-metaspeed-edge-tokyo',
    brand: 'ASICS', model: 'Metaspeed Edge Tokyo', year: 2026, category: 'race',
    cushioning: 8, dropMM: 5, weightGrams: 190,
    pronation: ['neutral'], terrain: ['road', 'track'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'], widthOptions: false, priceUSD: 250,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Carbon plate', 'FF Turbo Plus foam', 'Cadence-style racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'brooks-glycerin-22',
    brand: 'Brooks', model: 'Glycerin 22', year: 2026, category: 'max-cushion',
    cushioning: 9, dropMM: 10, weightGrams: 295,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'recovery'], widthOptions: true, priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['DNA Tuned nitrogen foam', 'Plush long-run feel', 'Wide sizes'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'brooks-hyperion-max-3',
    brand: 'Brooks', model: 'Hyperion Max 3', year: 2026, category: 'speed',
    cushioning: 7, dropMM: 8, weightGrams: 230,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['tempo', 'speed-work', 'race-day'], widthOptions: false, priceUSD: 175,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['DNA Flash v2', 'Plate-free uptempo', 'Lightweight'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'saucony-endorphin-speed-5',
    brand: 'Saucony', model: 'Endorphin Speed 5', year: 2026, category: 'speed',
    cushioning: 7, dropMM: 8, weightGrams: 232,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['tempo', 'speed-work', 'race-day'], widthOptions: false, priceUSD: 180,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['PWRRUN PB foam', 'Nylon plate', 'Daily-to-race versatility'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'saucony-endorphin-pro-5',
    brand: 'Saucony', model: 'Endorphin Pro 5', year: 2026, category: 'race',
    cushioning: 8, dropMM: 8, weightGrams: 218,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'], widthOptions: false, priceUSD: 230,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Carbon plate', 'PWRRUN HG supercritical', 'Marathon racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'on-cloudboom-strike-ls',
    brand: 'On', model: 'Cloudboom Strike LS', year: 2026, category: 'race',
    cushioning: 8, dropMM: 4, weightGrams: 170,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'], widthOptions: false, priceUSD: 330,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['LightSpray seamless upper', 'Speedboard plate', 'Ultralight racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'on-cloudeclipse-2',
    brand: 'On', model: 'Cloudeclipse 2', year: 2026, category: 'max-cushion',
    cushioning: 9, dropMM: 6, weightGrams: 295,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'recovery'], widthOptions: false, priceUSD: 180,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Double Helion foam', 'Cushioned daily', 'Smooth rocker'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nb-supercomp-trainer-v3',
    brand: 'New Balance', model: 'FuelCell SuperComp Trainer v3', year: 2026, category: 'max-cushion',
    cushioning: 10, dropMM: 6, weightGrams: 310,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run'], widthOptions: true, priceUSD: 200,
    injuryFriendly: ['knee-pain', 'achilles'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Energy Arc carbon plate', 'PEBA midsole', 'Stacked super trainer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'adidas-evo-sl-2',
    brand: 'Adidas', model: 'Adizero Evo SL 2', year: 2026, category: 'speed',
    cushioning: 7, dropMM: 6, weightGrams: 215,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'tempo', 'speed-work'], widthOptions: false, priceUSD: 160,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Lightstrike Pro foam', 'Plate-free uptempo', 'Daily-to-race versatility'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'hoka-mach-x-2',
    brand: 'Hoka', model: 'Mach X 2', year: 2026, category: 'speed',
    cushioning: 8, dropMM: 5, weightGrams: 260,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['tempo', 'speed-work', 'long-run'], widthOptions: false, priceUSD: 190,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Pebax plate', 'PEBA-blend foam', 'Versatile super trainer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'nnormal-kjerag-2',
    brand: 'NNormal', model: 'Kjerag 2', year: 2026, category: 'trail',
    cushioning: 7, dropMM: 6, weightGrams: 220,
    pronation: ['neutral'], terrain: ['trail'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['trail', 'ultra', 'race-day'], widthOptions: false, priceUSD: 195,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Vibram Litebase Megagrip', 'EExpure midsole', 'Kilian-tested ultra racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'salomon-s-lab-genesis',
    brand: 'Salomon', model: 'S/Lab Genesis', year: 2026, category: 'trail',
    cushioning: 7, dropMM: 8, weightGrams: 245,
    pronation: ['neutral'], terrain: ['trail'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['trail', 'ultra'], widthOptions: false, priceUSD: 200,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Energy Foam', 'Contagrip MA', 'Long-distance trail racer'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'puma-fast-r-nitro-elite-3',
    brand: 'Puma', model: 'Fast-R Nitro Elite 3', year: 2026, category: 'race',
    cushioning: 8, dropMM: 8, weightGrams: 195,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'], widthOptions: false, priceUSD: 275,
    injuryFriendly: [], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Decoupled carbon plate', 'Nitro Elite + A-Foam', 'Marathon super shoe'],
    lastVerified: '2026-05-04',
  },
  {
    id: 'mizuno-neo-vista-2',
    brand: 'Mizuno', model: 'Neo Vista 2', year: 2026, category: 'max-cushion',
    cushioning: 9, dropMM: 8, weightGrams: 265,
    pronation: ['neutral'], terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run', 'tempo'], widthOptions: false, priceUSD: 185,
    injuryFriendly: ['knee-pain'], amazonASIN: 'SEARCH',
    reviewURL: 'https://gearuptofit.com/review/best-running-shoes/',
    imageURL: '/images/shoes/placeholder.jpg',
    highlights: ['Enerzy NXT foam', 'Plate-free super trainer', 'Bouncy long-run'],
    lastVerified: '2026-05-04',
  },
];

/**
 * Returns a guaranteed-valid Amazon affiliate URL using a search query.
 * Search-based links never 404 (unlike ASIN-based links when products are
 * delisted or replaced by newer versions). All revenue routes through papalex-20.
 */
export function getAmazonLink(brand: string, model: string, affiliateTag: string = 'papalex-20'): string {
  const query = encodeURIComponent(`${brand} ${model} running shoes`);
  return `https://www.amazon.com/s?k=${query}&tag=${affiliateTag}`;
}

/** Convenience helper that takes a Shoe directly. */
export function getShoeAmazonLink(shoe: Pick<Shoe, 'brand' | 'model'>, affiliateTag: string = 'papalex-20'): string {
  return getAmazonLink(shoe.brand, shoe.model, affiliateTag);
}
