export interface Shoe {
  id: string;
  brand: string;
  model: string;
  year: number;
  category: 'daily' | 'speed' | 'race' | 'trail' | 'max-cushion' | 'stability' | 'hybrid';
  cushioning: number; // 1-10
  dropMM: number;
  weightGrams: number;
  pronation: ('neutral' | 'overpronation' | 'underpronation')[];
  terrain: ('road' | 'trail' | 'track')[];
  bestDistances: string[];
  bestFor: string[];
  widthOptions: boolean;
  priceUSD: number;
  injuryFriendly: string[];
  amazonASIN: string;
  reviewURL: string;
  imageURL: string;
  highlights: string[];
}

export const shoeDatabase: Shoe[] = [
  // === NIKE ===
  {
    id: 'nike-pegasus-41',
    brand: 'Nike',
    model: 'Pegasus 41',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 285,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['beginner', 'daily', 'long-run'],
    widthOptions: true,
    priceUSD: 130,
    injuryFriendly: ['knee-pain', 'shin-splints'],
    amazonASIN: 'B0D5Y2KZQH',
    reviewURL: 'https://gearuptofit.com/review/nike-pegasus-41/',
    imageURL: '/images/shoes/nike-pegasus-41.jpg',
    highlights: ['ReactX foam', 'Versatile all-rounder', 'Great for beginners'],
  },
  {
    id: 'nike-pegasus-premium',
    brand: 'Nike',
    model: 'Pegasus Premium',
    year: 2025,
    category: 'daily',
    cushioning: 8,
    dropMM: 10,
    weightGrams: 275,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 180,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0DFLY4TQX',
    reviewURL: 'https://gearuptofit.com/review/nike-pegasus-premium/',
    imageURL: '/images/shoes/nike-pegasus-premium.jpg',
    highlights: ['ZoomX foam', 'Premium daily trainer', 'Plush ride'],
  },
  {
    id: 'nike-vomero-plus',
    brand: 'Nike',
    model: 'Vomero Plus',
    year: 2025,
    category: 'max-cushion',
    cushioning: 9,
    dropMM: 10,
    weightGrams: 305,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 180,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'],
    amazonASIN: 'B0DG1RSLWZ',
    reviewURL: 'https://gearuptofit.com/review/nike-vomero-plus/',
    imageURL: '/images/shoes/nike-vomero-plus.jpg',
    highlights: ['ZoomX midsole', 'Max cushion', 'Injury-friendly'],
  },
  {
    id: 'nike-pegasus-turbo',
    brand: 'Nike',
    model: 'Pegasus Turbo',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 8,
    weightGrams: 230,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'race-day'],
    widthOptions: false,
    priceUSD: 190,
    injuryFriendly: [],
    amazonASIN: 'B0DFLYH8QX',
    reviewURL: 'https://gearuptofit.com/review/running-shoes/nike-pegasus-turbo-review/',
    imageURL: '/images/shoes/nike-pegasus-turbo.jpg',
    highlights: ['ZoomX + React', 'Lightweight', 'Speed sessions'],
  },
  // === BROOKS ===
  {
    id: 'brooks-ghost-17',
    brand: 'Brooks',
    model: 'Ghost 17',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 12,
    weightGrams: 290,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['beginner', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['achilles', 'shin-splints'],
    amazonASIN: 'B0CX3T1GRV',
    reviewURL: 'https://gearuptofit.com/review/brooks-ghost-17/',
    imageURL: '/images/shoes/brooks-ghost-17.jpg',
    highlights: ['DNA LOFT v2', 'Smooth transitions', 'Classic neutral'],
  },
  {
    id: 'brooks-glycerin-max-2',
    brand: 'Brooks',
    model: 'Glycerin Max 2',
    year: 2025,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 10,
    weightGrams: 310,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 170,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints'],
    amazonASIN: 'B0D8Y4JQRV',
    reviewURL: 'https://gearuptofit.com/review/brooks-glycerin-max-2/',
    imageURL: '/images/shoes/brooks-glycerin-max-2.jpg',
    highlights: ['Nitrogen-infused foam', 'Ultra plush', 'Max stack height'],
  },
  // === ASICS ===
  {
    id: 'asics-gel-nimbus-28',
    brand: 'Asics',
    model: 'Gel-Nimbus 28',
    year: 2025,
    category: 'daily',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 295,
    pronation: ['neutral', 'underpronation'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 160,
    injuryFriendly: ['knee-pain', 'plantar-fasciitis'],
    amazonASIN: 'B0CWG4XFQH',
    reviewURL: 'https://gearuptofit.com/review/asics-gel-nimbus-28/',
    imageURL: '/images/shoes/asics-gel-nimbus-28.jpg',
    highlights: ['FF BLAST PLUS ECO', 'PureGEL heel', 'Plush comfort'],
  },
  {
    id: 'asics-gel-kayano-32',
    brand: 'Asics',
    model: 'Gel-Kayano 32',
    year: 2025,
    category: 'stability',
    cushioning: 8,
    dropMM: 10,
    weightGrams: 310,
    pronation: ['overpronation'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 160,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'it-band'],
    amazonASIN: 'B0D4X7KLQH',
    reviewURL: 'https://gearuptofit.com/review/running-shoes/asics-mens-gel-kayano-32/',
    imageURL: '/images/shoes/asics-gel-kayano-32.jpg',
    highlights: ['4D Guidance System', 'FF BLAST PLUS', 'Premium stability'],
  },
  {
    id: 'asics-novablast-5',
    brand: 'Asics',
    model: 'Novablast 5',
    year: 2025,
    category: 'speed',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 260,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'daily'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0D6Y3KFQH',
    reviewURL: 'https://gearuptofit.com/review/asics-novablast-5/',
    imageURL: '/images/shoes/asics-novablast-5.jpg',
    highlights: ['FF BLAST PLUS', 'Bouncy ride', 'Tempo sessions'],
  },
  {
    id: 'asics-novablast-4',
    brand: 'Asics',
    model: 'Novablast 4',
    year: 2024,
    category: 'daily',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 265,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'speed-work'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0CTKR8QQH',
    reviewURL: 'https://gearuptofit.com/review/asics-novablast-4/',
    imageURL: '/images/shoes/asics-novablast-4.jpg',
    highlights: ['FF BLAST PLUS', 'Versatile', 'Great value'],
  },
  {
    id: 'asics-superblast-3',
    brand: 'Asics',
    model: 'Superblast 3',
    year: 2025,
    category: 'race',
    cushioning: 8,
    dropMM: 8,
    weightGrams: 240,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 200,
    injuryFriendly: [],
    amazonASIN: 'B0DG2RKLQH',
    reviewURL: 'https://gearuptofit.com/review/asics-superblast-3/',
    imageURL: '/images/shoes/asics-superblast-3.jpg',
    highlights: ['FF TURBO PLUS', 'Carbon plate', 'Super trainer'],
  },
  {
    id: 'asics-sonicblast',
    brand: 'Asics',
    model: 'Sonicblast',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 8,
    weightGrams: 235,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k'],
    bestFor: ['speed-work', 'race-day'],
    widthOptions: false,
    priceUSD: 160,
    injuryFriendly: [],
    amazonASIN: 'B0DH3RMLQH',
    reviewURL: 'https://gearuptofit.com/review/asics-sonicblast/',
    imageURL: '/images/shoes/asics-sonicblast.jpg',
    highlights: ['Lightweight racer', 'Fast turnover', 'Track-ready'],
  },
  {
    id: 'asics-megablast',
    brand: 'Asics',
    model: 'Megablast',
    year: 2025,
    category: 'max-cushion',
    cushioning: 9,
    dropMM: 8,
    weightGrams: 295,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 180,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain'],
    amazonASIN: 'B0DI4RNLQH',
    reviewURL: 'https://gearuptofit.com/review/asics-megablast/',
    imageURL: '/images/shoes/asics-megablast.jpg',
    highlights: ['Max stack', 'FF BLAST PLUS ECO', 'Ultra cushioned'],
  },
  // === HOKA ===
  {
    id: 'hoka-bondi-9',
    brand: 'Hoka',
    model: 'Bondi 9',
    year: 2025,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 4,
    weightGrams: 310,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['beginner', 'long-run', 'daily'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'achilles'],
    amazonASIN: 'B0DG5RPLQH',
    reviewURL: 'https://gearuptofit.com/review/hoka-bondi-9/',
    imageURL: '/images/shoes/hoka-bondi-9.jpg',
    highlights: ['Ultra-cushioned', 'Meta-Rocker', 'Recovery-friendly'],
  },
  {
    id: 'hoka-cielo-x1-3',
    brand: 'Hoka',
    model: 'Cielo X1 3',
    year: 2025,
    category: 'race',
    cushioning: 6,
    dropMM: 5,
    weightGrams: 195,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'B0DH6RQLQH',
    reviewURL: 'https://gearuptofit.com/review/hoka-cielo-x1-3/',
    imageURL: '/images/shoes/hoka-cielo-x1-3.jpg',
    highlights: ['Carbon plate', 'PEBA foam', 'Race-day weapon'],
  },
  // === SAUCONY ===
  {
    id: 'saucony-ride-19',
    brand: 'Saucony',
    model: 'Ride 19',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 270,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['beginner', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: ['shin-splints'],
    amazonASIN: 'B0D7Y5KLQH',
    reviewURL: 'https://gearuptofit.com/review/saucony-ride-19/',
    imageURL: '/images/shoes/saucony-ride-19.jpg',
    highlights: ['PWRRUN+', 'Smooth ride', 'Versatile trainer'],
  },
  {
    id: 'saucony-endorphin-azura',
    brand: 'Saucony',
    model: 'Endorphin Azura',
    year: 2025,
    category: 'race',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 210,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 230,
    injuryFriendly: [],
    amazonASIN: 'B0DI7RSLQH',
    reviewURL: 'https://gearuptofit.com/review/saucony-endorphin-azura/',
    imageURL: '/images/shoes/saucony-endorphin-azura.jpg',
    highlights: ['Carbon plate', 'PWRRUN HG', 'Elite racer'],
  },
  // === ON ===
  {
    id: 'on-cloudsurfer-2',
    brand: 'On',
    model: 'Cloudsurfer 2',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'beginner'],
    widthOptions: false,
    priceUSD: 150,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0CX5T3GRV',
    reviewURL: 'https://gearuptofit.com/review/on-cloudsurfer-2/',
    imageURL: '/images/shoes/on-cloudsurfer-2.jpg',
    highlights: ['CloudTec Phase', 'Helion HF', 'Swiss engineering'],
  },
  // === ADIDAS ===
  {
    id: 'adidas-adios-pro-4',
    brand: 'Adidas',
    model: 'Adios Pro 4',
    year: 2025,
    category: 'race',
    cushioning: 7,
    dropMM: 7,
    weightGrams: 195,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race-day'],
    widthOptions: false,
    priceUSD: 250,
    injuryFriendly: [],
    amazonASIN: 'B0D9Y6MLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-adios-pro-4/',
    imageURL: '/images/shoes/adidas-adios-pro-4.jpg',
    highlights: ['ENERGYRODS 2.0', 'LIGHTSTRIKE PRO', 'Marathon weapon'],
  },
  {
    id: 'adidas-adios-9',
    brand: 'Adidas',
    model: 'Adios 9',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 7,
    weightGrams: 235,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'race-day'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0DAY7NLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-adios-9/',
    imageURL: '/images/shoes/adidas-adios-9.jpg',
    highlights: ['LIGHTSTRIKE PRO', 'Glass fiber rods', 'Tempo specialist'],
  },
  {
    id: 'adidas-boston-13',
    brand: 'Adidas',
    model: 'Boston 13',
    year: 2025,
    category: 'speed',
    cushioning: 6,
    dropMM: 7,
    weightGrams: 245,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['speed-work', 'daily'],
    widthOptions: true,
    priceUSD: 140,
    injuryFriendly: [],
    amazonASIN: 'B0DBY8PLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-adizero-boston-13/',
    imageURL: '/images/shoes/adidas-boston-13.jpg',
    highlights: ['LIGHTSTRIKE PRO', 'Energyrods', 'Fast daily trainer'],
  },
  {
    id: 'adidas-evo-sl',
    brand: 'Adidas',
    model: 'EVO SL',
    year: 2025,
    category: 'daily',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 275,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily', 'beginner'],
    widthOptions: true,
    priceUSD: 120,
    injuryFriendly: ['shin-splints'],
    amazonASIN: 'B0DCY9QLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-evo-sl/',
    imageURL: '/images/shoes/adidas-evo-sl.jpg',
    highlights: ['DREAMSTRIKE+', 'Affordable', 'Great first shoe'],
  },
  {
    id: 'adidas-evo-sl-atr',
    brand: 'Adidas',
    model: 'EVO SL ATR',
    year: 2025,
    category: 'hybrid',
    cushioning: 7,
    dropMM: 10,
    weightGrams: 290,
    pronation: ['neutral'],
    terrain: ['road', 'trail'],
    bestDistances: ['5k', '10k', 'half-marathon'],
    bestFor: ['daily'],
    widthOptions: false,
    priceUSD: 130,
    injuryFriendly: [],
    amazonASIN: 'B0DDY0RLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-evo-sl-atr/',
    imageURL: '/images/shoes/adidas-evo-sl-atr.jpg',
    highlights: ['Continental rubber', 'Road-to-trail', 'Hybrid outsole'],
  },
  {
    id: 'adidas-takumi-sen-11',
    brand: 'Adidas',
    model: 'Takumi Sen 11',
    year: 2025,
    category: 'race',
    cushioning: 4,
    dropMM: 6,
    weightGrams: 175,
    pronation: ['neutral'],
    terrain: ['road', 'track'],
    bestDistances: ['5k', '10k'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 180,
    injuryFriendly: [],
    amazonASIN: 'B0DEY1SLQH',
    reviewURL: 'https://gearuptofit.com/review/adidas-takumi-sen-11/',
    imageURL: '/images/shoes/adidas-takumi-sen-11.jpg',
    highlights: ['Ultra lightweight', 'LIGHTSTRIKE PRO', 'Racing flat'],
  },
  // === PUMA ===
  {
    id: 'puma-deviate-elite-4',
    brand: 'Puma',
    model: 'Deviate Elite 4',
    year: 2025,
    category: 'race',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 205,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race-day'],
    widthOptions: false,
    priceUSD: 230,
    injuryFriendly: [],
    amazonASIN: 'B0DFY2TLQH',
    reviewURL: 'https://gearuptofit.com/review/puma-deviate-elite-4/',
    imageURL: '/images/shoes/puma-deviate-elite-4.jpg',
    highlights: ['NITRO ELITE foam', 'Carbon plate', 'Race day'],
  },
  {
    id: 'puma-deviate-nitro-elite-2',
    brand: 'Puma',
    model: 'Deviate Nitro Elite 2',
    year: 2024,
    category: 'race',
    cushioning: 7,
    dropMM: 8,
    weightGrams: 210,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon'],
    bestFor: ['race-day', 'speed-work'],
    widthOptions: false,
    priceUSD: 220,
    injuryFriendly: [],
    amazonASIN: 'B0CGY3ULQH',
    reviewURL: 'https://gearuptofit.com/review/puma-deviate-nitro-elite-2-review/',
    imageURL: '/images/shoes/puma-deviate-nitro-elite-2.jpg',
    highlights: ['NITRO ELITE', 'Carbon plate', 'Proven racer'],
  },
  {
    id: 'puma-magmax-2',
    brand: 'Puma',
    model: 'Magmax 2',
    year: 2025,
    category: 'daily',
    cushioning: 8,
    dropMM: 10,
    weightGrams: 285,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: false,
    priceUSD: 140,
    injuryFriendly: ['knee-pain'],
    amazonASIN: 'B0DGY4VLQH',
    reviewURL: 'https://gearuptofit.com/review/puma-magmax-2/',
    imageURL: '/images/shoes/puma-magmax-2.jpg',
    highlights: ['NITRO foam', 'Cushioned daily', 'Comfortable'],
  },
  // === NEW BALANCE ===
  {
    id: 'nb-fresh-foam-more-v6',
    brand: 'New Balance',
    model: 'Fresh Foam X More v6',
    year: 2025,
    category: 'max-cushion',
    cushioning: 10,
    dropMM: 4,
    weightGrams: 320,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['half-marathon', 'marathon', 'ultra'],
    bestFor: ['long-run', 'daily'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['plantar-fasciitis', 'knee-pain', 'shin-splints', 'achilles'],
    amazonASIN: 'B0DHY5WLQH',
    reviewURL: 'https://gearuptofit.com/review/new-balance-fresh-foam-x-more-v6/',
    imageURL: '/images/shoes/nb-more-v6.jpg',
    highlights: ['Fresh Foam X', 'Maximum stack', 'Recovery runs'],
  },
  {
    id: 'nb-1080-v14',
    brand: 'New Balance',
    model: '1080 v14',
    year: 2024,
    category: 'daily',
    cushioning: 8,
    dropMM: 6,
    weightGrams: 280,
    pronation: ['neutral'],
    terrain: ['road'],
    bestDistances: ['10k', 'half-marathon', 'marathon'],
    bestFor: ['daily', 'long-run'],
    widthOptions: true,
    priceUSD: 165,
    injuryFriendly: ['knee-pain', 'plantar-fasciitis'],
    amazonASIN: 'B0CTKR9QQH',
    reviewURL: 'https://gearuptofit.com/review/new-balance-1080-v14/',
    imageURL: '/images/shoes/nb-1080-v14.jpg',
    highlights: ['Fresh Foam X', 'Premium daily', 'Buttery smooth'],
  },
];

export function getAmazonLink(asin: string, affiliateTag: string = 'gearuptofit-20'): string {
  return `https://www.amazon.com/dp/${asin}?tag=${affiliateTag}`;
}
