project_id = "setcqniidanludicrdye"

[functions.brevo-subscribe]
verify_jwt = false

[functions.brevo-webhook]
verify_jwt = false

[functions.marketing-drip-dispatcher]
verify_jwt = false

[functions.marketing-finalize]
verify_jwt = false

[functions.upgrade-brevo-templates]
verify_jwt = false
